### ISSUE TITLE
How to display a 3d object at different locations

### ISSUE THREAD

**Issue by galleon** [uber/deck.gl#2766]
I am trying to display a moving 3d object on a map using [lon, lat, altitude]. I have identified either the MeshLayer and ScenegraphLayer as potential tools.
Any advice on which one seems the best?
- With MeshLayer I am struggling in finding the best way to loaf a GLB file and transform it to a geometry,
 - ScenegraphLayer seems quite new and I am missing the GLTFInstantiator. I got the following error message:
./src/components/scenegraph-layer/scenegraph-layer.js
Attempted import error: 'GLTFInstantiator' is not exported from 'luma.gl'.

Here is my package.json:
  "dependencies": {
    "@deck.gl/experimental-layers": "^6.4.5",
    "@loaders.gl/core": "^0.8.0",
    "@loaders.gl/gltf": "^0.8.0",
    "colorbrewer": "^1.3.0",
    "deck.gl": "^6.4.5",
    "loaders.gl": "^0.3.5",
    "luma.gl": "^6.4.3",
    "react": "^16.8.4",
    "react-autobind": "^1.0.6",
    "react-dom": "^16.8.4",
    "react-map-gl": "^4.0.14",
    "react-scripts": "2.1.8",
    "react-stats-zavatta": "^0.0.6"
  },

I have also tried (without success) the latest code:
├─ @deck.gl/aggregation-layers@7.0.0-alpha.4
├─ @deck.gl/geo-layers@7.0.0-alpha.4
├─ @deck.gl/layers@7.0.0-alpha.4
├─ @deck.gl/mapbox@7.0.0-alpha.4
├─ @deck.gl/mesh-layers@7.0.0-alpha.4
├─ @deck.gl/react@7.0.0-alpha.4
├─ @loaders.gl/gltf@0.7.2
├─ @luma.gl/constants@7.0.0-alpha.8
├─ colorbrewer@1.3.0
├─ react-autobind@1.0.6
├─ react-dom@16.8.4
├─ react-map-gl@4.0.14
├─ react-scripts@2.1.8
├─ react-stats-zavatta@0.0.6
└─ react@16.8.4

**Comment by ibgreen** [comment]
@galleon You are looking at the master branch, where we are actively putting the finishing touches on the glTF support in luma.gl and the companion `ScenegraphLayer` in deck.gl.

So I can't guarantee that things will work, but I can say that if you are using a 7.0-alpha version of deck.gl you also have to use a 7.0-alpha version of luma.gl.

Hope that helps.

**Comment by galleon** [comment]
Thanks for the quick answer.
When moving a piece of code inspired from  `examples/layer-browser` https://github.com/galleon/flightview to 7.0.0-alpha I got the following error. Any change in DeckGL ?

Uncaught TypeError: this.stats.timeStart is not a function
    at Deck.setProps (deck.js:211)
    at new Deck (deck.js:178)
    at DeckGL.componentDidMount (deckgl.js:156)
    at commitLifeCycles (react-dom.development.js:18071)
    at commitAllLifeCycles (react-dom.development.js:19630)
    at HTMLUnknownElement.callCallback (react-dom.development.js:147)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:196)
    at invokeGuardedCallback (react-dom.development.js:250)
    at commitRoot (react-dom.development.js:19854)
    at react-dom.development.js:21402
    at Object.unstable_runWithPriority (scheduler.development.js:255)
    at completeRoot (react-dom.development.js:21401)
    at performWorkOnRoot (react-dom.development.js:21324)
    at performWork (react-dom.development.js:21229)
    at performSyncWork (react-dom.development.js:21203)
    at requestWork (react-dom.development.js:21058)
    at scheduleWork (react-dom.development.js:20871)
    at scheduleRootUpdate (react-dom.development.js:21566)
    at updateContainerAtExpirationTime (react-dom.development.js:21592)
    at updateContainer (react-dom.development.js:21660)
    at ReactRoot.push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render (react-dom.development.js:21973)
    at react-dom.development.js:22125
    at unbatchedUpdates (react-dom.development.js:21448)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:22121)
    at Object.render (react-dom.development.js:22196)
    at render (index.js:34)
    at Module../src/index.js (index.js:37)
    at __webpack_require__ (bootstrap:781)
    at fn (bootstrap:149)
    at Object.0 (index.js:23)
    at __webpack_require__ (bootstrap:781)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
deckgl.js:168 Uncaught TypeError: Cannot read property 'finalize' of undefined
    at DeckGL.componentWillUnmount (deckgl.js:168)
    at callComponentWillUnmountWithTimer (react-dom.development.js:17888)
    at HTMLUnknownElement.callCallback (react-dom.development.js:147)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:196)
    at invokeGuardedCallback (react-dom.development.js:250)
    at safelyCallComponentWillUnmount (react-dom.development.js:17895)
    at commitUnmount (react-dom.development.js:18325)
    at commitNestedUnmounts (react-dom.development.js:18361)
    at unmountHostComponents (react-dom.development.js:18648)
    at commitDeletion (react-dom.development.js:18712)
    at commitAllHostEffects (react-dom.development.js:19577)
    at HTMLUnknownElement.callCallback (react-dom.development.js:147)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:196)
    at invokeGuardedCallback (react-dom.development.js:250)
    at commitRoot (react-dom.development.js:19816)
    at react-dom.development.js:21402
    at Object.unstable_runWithPriority (scheduler.development.js:255)
    at completeRoot (react-dom.development.js:21401)
    at performWorkOnRoot (react-dom.development.js:21324)
    at performWork (react-dom.development.js:21229)
    at performSyncWork (react-dom.development.js:21203)
    at requestWork (react-dom.development.js:21058)
    at scheduleWork (react-dom.development.js:20871)
    at scheduleRootUpdate (react-dom.development.js:21566)
    at updateContainerAtExpirationTime (react-dom.development.js:21592)
    at updateContainer (react-dom.development.js:21660)
    at ReactRoot.push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render (react-dom.development.js:21973)
    at react-dom.development.js:22125
    at unbatchedUpdates (react-dom.development.js:21448)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:22121)
    at Object.render (react-dom.development.js:22196)
    at render (index.js:34)
    at Module../src/index.js (index.js:37)
    at __webpack_require__ (bootstrap:781)
    at fn (bootstrap:149)
    at Object.0 (index.js:23)
    at __webpack_require__ (bootstrap:781)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
2index.js:1446 The above error occurred in the <DeckGL> component:
    in DeckGL (at App.js:426)
    in div (at App.js:425)
    in div (at App.js:469)
    in App (at src/index.js:23)
    in div (at src/index.js:21)
    in Root (at src/index.js:34)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
function.console.(anonymous function) @ index.js:1446
react-dom.development.js:21289 Uncaught TypeError: this.stats.timeStart is not a function
    at Deck.setProps (deck.js:211)
    at new Deck (deck.js:178)
    at DeckGL.componentDidMount (deckgl.js:156)
    at commitLifeCycles (react-dom.development.js:18071)
    at commitAllLifeCycles (react-dom.development.js:19630)
    at HTMLUnknownElement.callCallback (react-dom.development.js:147)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:196)
    at invokeGuardedCallback (react-dom.development.js:250)
    at commitRoot (react-dom.development.js:19854)
    at react-dom.development.js:21402
    at Object.unstable_runWithPriority (scheduler.development.js:255)
    at completeRoot (react-dom.development.js:21401)
    at performWorkOnRoot (react-dom.development.js:21324)
    at performWork (react-dom.development.js:21229)
    at performSyncWork (react-dom.development.js:21203)
    at requestWork (react-dom.development.js:21058)
    at scheduleWork (react-dom.development.js:20871)
    at scheduleRootUpdate (react-dom.development.js:21566)
    at updateContainerAtExpirationTime (react-dom.development.js:21592)
    at updateContainer (react-dom.development.js:21660)
    at ReactRoot.push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render (react-dom.development.js:21973)
    at react-dom.development.js:22125
    at unbatchedUpdates (react-dom.development.js:21448)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:22121)
    at Object.render (react-dom.development.js:22196)
    at render (index.js:34)
    at Module../src/index.js (index.js:37)
    at __webpack_require__ (bootstrap:781)
    at fn (bootstrap:149)
    at Object.0 (index.js:23)
    at __webpack_require__ (bootstrap:781)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
index.js:1446 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in FPSStats (at src/index.js:22)
    in div (at src/index.js:21)
    in Root (at src/index.js:34)

**Comment by ibgreen** [comment]
You probably need an alpha version of probe.gl. We are working on v7.0, it is a major release and there are changes in many places, so you may need to chase down a few of these.

**Comment by galleon** [comment]
Thanks! It seems that probe.gl is imported as yarn.lock shows. What is weird is that it shows twice.
Is that normal ?

probe.gl@3.0.0-alpha.5:
  version "3.0.0-alpha.5"
  resolved "https://registry.yarnpkg.com/probe.gl/-/probe.gl-3.0.0-alpha.5.tgz#0e79879fa0c3977da3ced90e3276503364d42fa3"
  integrity sha512-CH/IJWw80KQkDD4TU+YmrtmALNDsGyxaNJAu/LqkCsgZ+0JQf75XUJ1D97FN8aRKb08Nc8fkHOMYbIXbUMW49A==
  dependencies:
    "@babel/runtime" "^7.0.0"

probe.gl@^3.0.0-alpha.5:
  version "3.0.0-alpha.6"
  resolved "https://registry.yarnpkg.com/probe.gl/-/probe.gl-3.0.0-alpha.6.tgz#1658518b19f577c85bdcd20629db396bbffa6552"
  integrity sha512-WgIj1LnM4wBNOMAkF/titGvK/ykkB5q4X7VcOzTYNNhyYMhSYQxWZBS3MR4eri7xEviZZmBAUtkT5ez8DutUYg==
  dependencies:
    "@babel/runtime" "^7.0.0"

**Comment by KrausMatthias** [comment]
Uncaught TypeError: this.stats.timeStart is not a function also shows up on various examples in https://github.com/uber/deck.gl/tree/master/examples/website/ (I tried trips and line)

**Comment by tsherif** [comment]
This version of deck is using the old probe.gl Stats API, but seems to be importing a newer alpha of probe.gl. If you make it use exactly `3.0.0-alpha.5`, it should get rid of those errors (IIRC `alpha.6` is where the Stats API was refactored).

**Comment by ibgreen** [comment]
@galleon @KrausMatthias: Just curious, did you explicitly install v7 alpha releases of deck.gl and luma.gl, or were these installed without you specifying, or are you building from master?

If you install the latest alpha release and reinstall (remove yarn.lock and node_modules to be sure), all dependencies should be resolved appropriately. 

Trying to manually match alpha releases of our various in-development modules sounds quite painful.

Or you can just wait ~ two weeks for our official v7.0 release.

**Comment by galleon** [comment]
@ibgreen Yes I did some tests installing v7 alpha releases but at some point I was in need to use the code in master (see #2784). I tried several ways to get this:
  - first trying to clone with the idea to publish - but this was not possible as I dont own the deck.gl scope ;-)
  - second by trying to install from the git repo directly - but that does not seem possible for modules (using yarn add git+https://github.com/uber/deck.gl/modules/core)
  - third trying to add from my cloned repo (see https://stackoverflow.com/questions/55177348/managing-javascript-dependencies)

I have still not find a way to use the master code in a project without having to wait for the team to push a release.

**Comment by ibgreen** [comment]
@galleon Ha ha, yes please don't publish releases on our behalf, that would be very confusing for others. In spite of your difficulties, we do work hard to make things work before we publish ;)

Linking to another repo is rather tricky especially as deck.gl is a monorepo with many modules. Our examples are however set up to do exactly this, there is a `start-local` script in every repo and it makes their webpack files import a `webpack.config.local.js` that sets up "aliases" to the various deck.gl modules.

It would be a bit of work, especially if you are new to webpack, but it might be a way forward. If you put your app in one of the example folders and copied our webpack setup you might be able to get it to work fairly quickly that way.

But better yet, keep checking for new alpha releases. Chances are that the issues you saw are fixed in the next release.

**Comment by ibgreen** [comment]
I believe that deck.gl@7.0.0-alpha.5 was just published, maybe give it a go?
