### ISSUE TITLE
current version and higher than 4.0.0 doesn't work in older browser "this.state.model.renderer is null" 

### ISSUE THREAD

**Issue by SlavaDev** [uber/deck.gl#966]
Hello, I have a problem, after update from 4.0.0 to 4.1.2, I can't run it in older browsers like IE11 and firefox 48. In the console: "this.state.model.renderer is undefined or null" in the file 'webpack:///~/deck.gl/dist/layers/core/solid-polygon-layer/solid-polygon-layer.js'

**Comment by ibgreen** [comment]
@SlavaDev We focus on supporting so called "evergreen" browsers, and we expect users to stay reasonably up to date. With this in mind:
* Firefox: With Firefox currently being on v55 we can't justify debugging an issue on Firefox v48. That said, it is probably a very minor breakage, so if you or someone else was able to find the issue and the fix turns out to be simple, we would of course accept a PR (or even considering making a PR if the problem description was clear enough).
* IE11: This is the one exception to our "evergreen" policy. We would really like to support IE11 as the one non-evergreen browser. The effort is likely small. Unfortunately a lack of access to Windows machines on our side keeps this from happening. Again we'd happily take PRs here.

**Comment by SlavaDev** [comment]
Hello, seems like problem on luma.gl. After investigate I found:  ```
'deck.gl error while initializing ScatterplotLayer({id: 'scatterplotLayer'})
 Error: Could not parse GLSL compiler error: Shader compilation errors
(27, 1): Unknown extension: GL_OES_standard_derivatives
(27, 48): Internal compiler error
(36, 1): Required extension GL_EXT_draw_buffers is not supported
(36, 41): Internal compiler error'
```

**Comment by ibgreen** [comment]
@SlavaDev Thanks for investigating. Yes this is a luma.gl issue. It seems that the shader compiler is seeing the request to enable the extension even though that line is under `#ifdef` https://github.com/uber/luma.gl/blob/master/src/shadertools/lib/platform-defines.js#L86

This is pretty easy to fix and could be addressed in the next luma.gl patch release (maybe within a week or so).

Would you consider opening the issue in luma?

**Comment by ibgreen** [comment]
@1chandu

**Comment by SlavaDev** [comment]
@ibgreen Sure
